name: Centralized workflow
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ui:
    uses: folio-org/.github/.github/workflows/ui.yml@v1
    # on the main branch, only run on push and tag events, to prevent duplicate runs
    if: github.ref_name == github.event.repository.default_branch || github.event_name != 'push' || github.ref_type == 'tag'
    secrets: inherit
    with:
      jest-enabled: false
      bigtest-enabled: true
      bigtest-test-command: xvfb-run --server-args="-screen 0 1024x768x24" yarn test
      sonar-sources: ./lib
      compile-translations: false
      generate-module-descriptor: false
      install-before-publish: true
